#!/bin/bash
### SEXY REPO START HELPER (assumes you are starting a branch on the project you're in if you ommit that argument)
rst()
{
if [ $# -eq 1 ]; then
    pushd . &> /dev/null 
    while [ 1 ]; do
        if [ -d .git ] || [ `pwd` = / ]; then break; fi
        cd ..
    done
    [ `pwd` = / ] && return 1
    currpath=`pwd`
    while [ 1 ]; do
        if [ -d .repo ] || [ `pwd` = / ]; then break; fi
        cd ..
    done
    [ `pwd` = / ] && return 1
    saferepopath=`pwd | sed 's/\//\\\\\//g'`
    currpath=`echo $currpath | sed "s/$saferepopath//g" | sed 's/^\///g'`
    repo start $1 $currpath
    popd &> /dev/null
else
    repo start $1 $*
fi
}

### SEXY REPO UPLOAD HELPER!
rup()
{
if [ $# -eq 0 ]; then
    pushd . &> /dev/null 
    while [ 1 ]; do
        if [ -d .git ] || [ `pwd` = / ]; then break; fi
        cd ..
    done
    [ `pwd` = / ] && return 1
    currpath=`pwd`
    while [ 1 ]; do
        if [ -d .repo ] || [ `pwd` = / ]; then break; fi
        cd ..
    done
    [ `pwd` = / ] && return 1
    saferepopath=`pwd | sed 's/\//\\\\\//g'`
    currpath=`echo $currpath | sed "s/$saferepopath//g" | sed 's/^\///g'`
    repo upload $currpath
    popd &> /dev/null
else
    repo upload $*
fi
}
