#!/bin/bash
if [ $# -ne 5 ]; then
echo 'folder=$1 #folder containing part[0-9]*
deviceresolution=$2 # WxH - exact!
imagescale=$3 # 0.5 == images in zip are half as big as they will be drawn on the phone
framerate=$4
quality=$5     #1-100'
exit 0;
fi
folder=$1 #folder containing part[0-9]*
deviceresolution=$2 # WxH - exact!
imagescale=$3 #1-100
quality=$4     #1-100
framerate=$5
wholebefore=`du -h $deviceresolution.zip | cut -f 1`
pushd . >& /dev/null
cd $folder
mkdir -p /tmp/zipout
for x in `find -name '*.png'`; do
  mkdir -p `dirname /tmp/zipout/$x`
  before=`du -h $x | cut -f 1`
  newpath=`dirname /tmp/zipout/$x`/`basename $x .png`.jpg
  convert -strip -gaussian-blur 0.05 -compress JPEG -quality $quality% -resize $deviceresolution -resize $imagescale% $x $newpath
  after=`du -h $newpath | cut -f 1`
  echo "$x        $before ==> $after"
done
echo "$deviceresolution $framerate" | sed 's/x/ /g' > /tmp/zipout/desc.txt
last=
for x in part*; do
  if [ $last ]; then
     echo "p 1 0 $last" >> /tmp/zipout/desc.txt
  fi
  last=$x
done
echo "p 0 0 $last" >> /tmp/zipout/desc.txt
echo "" >> /tmp/zipout/desc.txt
cat /tmp/zipout/desc.txt
cd /tmp/zipout
find -name '*.tmp' -delete
makebootani
popd
mv /tmp/zipout/bootanimation.zip $deviceresolution.zip
rm -Rf /tmp/zipout
echo "$deviceresolution ani       $wholebefore ==> `du -h $deviceresolution.zip | cut -f 1`"
